# Generated by Django 4.2.3 on 2023-09-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_advert_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advert',
            table='advertisements',
        ),
    ]
